config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/search' => 'articles#search'

  resources :pages, only: [:index, :show]
  resources :articles do
    collection do
      get :search_suggestions
    end
  end

  resources :authors, only: [:index]

  get 'components' => 'components#components', as: :components
  get 'admin' => 'administrator/articles#index', as: :admin

  namespace :administrator do
    resources :authors
    resources :articles, except: :show
    resources :pages, except: :show
  end
end

app/models/author.rb
# frozen_string_literal: true

class Author < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  has_many :articles
  has_many :pages
  validates :name, presence: true

  scope :active, -> { where(active: true) }
end

app/controllers/administrator/articles_controller.rb
# frozen_string_literal: true

class Administrator::ArticlesController < Administrator::BaseController
  before_action :load_article, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order("id desc").
                paginate(page: params[:page], per_page: 20)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(permitted_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(permitted_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to administrator_articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def permitted_params
    params.require(:article).
      permit(:title, :subtitle, :body, :published, :author_id, :hero_image_name, :featured)
  end
end

app/controllers/administrator/authors_controller.rb
# frozen_string_literal: true

class Administrator::AuthorsController < Administrator::BaseController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.active.paginate(page: params[:page])
  end

  def show; end

  def new
    @author = Author.new
  end

  def edit; end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to administrator_author_path(@author), notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to administrator_author_path(@author), notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to administrator_authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.require(:author).permit(:name, :email, :active, :twitter, :about)
  end
end

app/controllers/administrator/base_controller.rb
# frozen_string_literal: true

class Administrator::BaseController < ApplicationController
  before_action :authenticate, if: -> { Rails.env.production? }

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "dox_blog" && password == "hgf765"
    end
  end
end

app/controllers/administrator/pages_controller.rb
# frozen_string_literal: true

class Administrator::PagesController < Administrator::BaseController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.published.paginate(page: params[:page])
  end

  def new
    @page = Page.new
  end

  def edit; end

  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to administrator_pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :subtitle, :body, :published, :author_id, :hero_image_name, :featured)
  end
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  def index
    @authors = Author.active.order('name asc').
               paginate(page: params[:page], per_page: 20)
  end
end

app/views/administrator/authors/_form.html.slim
.big
  = form_for @author, url: (@author.persisted?? administrator_author_path(@author) : administrator_authors_path) do |form|
    - if @author.errors.any?
      .error_explanation
        p = "#{pluralize(@author.errors.count, "error")} prohibited this author from being saved:"
        ul
          - @author.errors.full_messages.each do |message|
            li = message
    p
      = form.label :name
      = form.text_field :name
    p
      = form.label :email
      = form.text_field :email
    p
      = form.label :twitter, "Twitter (sans @)"
      = form.text_field :twitter
    p
      = form.label :about
      = form.text_area :about
    p
      = form.label :active do
      = form.check_box :active
    p
      = form.submit

app/views/administrator/authors/edit.html.slim
.row
  .section
    h1 Editing author
    hr
    == render 'form'
    hr
    = link_to 'Show', administrator_author_path(@author), class: 'btn'
    =< link_to 'Back', administrator_authors_path, class: 'btn'

app/views/administrator/authors/index.html.slim
= render "layouts/admin_menu"

.row
  .section

    = link_to 'New Author', new_administrator_author_path, class: 'btn'
    hr

    table.full
      thead
        tr
          th Name
          th Email
          th Active
          th
          th
          th

      tbody
        - @authors.each do |author|
          tr
            td = author.name
            td = author.email
            td = author.active
            td = link_to 'Show', administrator_author_path(author)
            td = link_to 'Edit', edit_administrator_author_path(author)
            td = link_to 'Destroy', administrator_author_path(author), data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/administrator/authors/new.html.slim
.row
  .section
    h1 New Author
    hr
    == render 'form'
    hr
    = link_to 'Cancel', administrator_authors_path, class: 'btn'

app/views/administrator/authors/show.html.slim
.row
  .section
    p
      strong> Name:
      = @author.name
    p
      strong> Email:
      = @author.email
    p
      strong> Active:
      = @author.active
    hr
    = link_to 'Edit', edit_administrator_author_path(@author), class: 'btn'
    =< link_to 'Back', administrator_authors_path, class: 'btn'