config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/search' => 'articles#search'

  resources :pages, only: [:index, :show]
  resources :articles do
    collection do
      get :search_suggestions
    end
  end

  resources :authors, only: [:index]

  get 'components' => 'components#components', as: :components
  get 'admin' => 'administrator/articles#index', as: :admin

  namespace :administrator do
    resources :authors
    resources :articles, except: :show
    resources :pages, except: :show
  end
end

app/models/article.rb
# frozen_string_literal: true

class Article < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  belongs_to :author
  validates :author, :title, :body, presence: true

  scope :published, -> { where(published: true).order("created_at desc") }
  scope :featured, -> { where(published: true).where(featured: true).order("id desc") }
end

app/controllers/administrator/articles_controller.rb
# frozen_string_literal: true

class Administrator::ArticlesController < Administrator::BaseController
  before_action :load_article, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order("id desc").
                paginate(page: params[:page], per_page: 20)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(permitted_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(permitted_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to administrator_articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def permitted_params
    params.require(:article).
      permit(:title, :subtitle, :body, :published, :author_id, :hero_image_name, :featured)
  end
end

app/controllers/administrator/authors_controller.rb
# frozen_string_literal: true

class Administrator::AuthorsController < Administrator::BaseController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.active.paginate(page: params[:page])
  end

  def show; end

  def new
    @author = Author.new
  end

  def edit; end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to administrator_author_path(@author), notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to administrator_author_path(@author), notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to administrator_authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.require(:author).permit(:name, :email, :active, :twitter, :about)
  end
end

app/controllers/administrator/base_controller.rb
# frozen_string_literal: true

class Administrator::BaseController < ApplicationController
  before_action :authenticate, if: -> { Rails.env.production? }

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "dox_blog" && password == "hgf765"
    end
  end
end

app/controllers/administrator/pages_controller.rb
# frozen_string_literal: true

class Administrator::PagesController < Administrator::BaseController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.published.paginate(page: params[:page])
  end

  def new
    @page = Page.new
  end

  def edit; end

  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to administrator_pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :subtitle, :body, :published, :author_id, :hero_image_name, :featured)
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true
class ArticlesController < ApplicationController
  before_action :load_article, only: :show
  protect_from_forgery with: :null_session # FIXME: allow testing with curl 
  def index
    @featured_article = Article.featured.limit(1).first
    @articles = Article.published.where.not(id: @featured_article).
      paginate(page: params[:page], per_page: 5)
  end

  def show
  end

  def search
    @articles = Article.all
    @articles = @articles.filter { |article|
      if params.has_key?('q')
        article[:score] = (article[:title].scan(params['q']).size)*2 + (article[:body].scan(params['q'])).size
        article[:title].downcase.scan(params['q']) or article[:body].downcase.scan(params['q'])
      end
        article[:score] > 0
    }
    if params.has_key? 'algo' 
      @articles.sort_by!{ |article| -article[:score] }
    end

    render json: @articles 
  end
end

app/views/administrator/articles/_form.html.slim
.big
  = form_for @article, url: (@article.persisted?? administrator_article_path(@article) : administrator_articles_path) do |form|
    - if @article.errors.any?
      .error_explanation
        p = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
        ul
          - @article.errors.full_messages.each do |message|
            li = message
    p
      = form.label :title do
      = form.text_field :title
    p
      = form.label :subtitle do
      = form.text_field :subtitle
    p
      = form.label :hero_image_name do
      = form.select :hero_image_name,
        options_from_collection_for_select(HeroImage.limit(200), "name", "name", @article.hero_image_name), prompt: "Select a hero image"
    p
      = form.label :body do
      = form.text_area :body, rows: '20'
    p
      = form.label :published do
      = form.check_box :published
    p
      = form.label :featured do
      = form.check_box :featured
    p
      = form.label :created_at do
      = form.text_field :created_at
    p
      = form.label :author do
      = collection_select(:article, :author_id, Author.active, :id, :name, prompt: true)
    p
      = form.submit

app/views/administrator/articles/edit.html.slim
.row
  .section
    h1 Editing Article
    hr
    = render 'form'
    hr
    = link_to 'Preview Article', article_path(@article), class: 'btn'
    =< link_to 'Cancel', administrator_articles_path, class: 'btn gray no-outline'

app/views/administrator/articles/index.html.slim
- provide :body_class do
  | articles-list articles

= render "layouts/admin_menu"

.row
  .section

    = link_to 'New Article', new_administrator_article_path, class: 'btn'
    hr

    .col-3-4
      - @articles.each do |article|
        .article
          h1 = article.title
          p.meta
            > Author:
            = article.author.try(:name)
            span.stick<
              > |
            > Published:
            = article.published
          p
            => link_to 'Preview', article_path(article), class: 'btn small'
            => link_to 'Edit', edit_administrator_article_path(article), class: 'btn small'
            => link_to 'Destroy', administrator_article_path(article), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn small red'
        hr
    .col-1-4

.row
  .section
    = will_paginate

app/views/administrator/articles/new.html.slim
.row
  .section
    h1 New Article
    hr
    = render 'form'
    hr
    = link_to 'Cancel', administrator_articles_path, class: 'btn'