config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/search' => 'articles#search'

  resources :pages, only: [:index, :show]
  resources :articles do
    collection do
      get :search_suggestions
    end
  end

  resources :authors, only: [:index]

  get 'components' => 'components#components', as: :components
  get 'admin' => 'administrator/articles#index', as: :admin

  namespace :administrator do
    resources :authors
    resources :articles, except: :show
    resources :pages, except: :show
  end
end

app/controllers/administrator/articles_controller.rb
# frozen_string_literal: true

class Administrator::ArticlesController < Administrator::BaseController
  before_action :load_article, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order("id desc").
                paginate(page: params[:page], per_page: 20)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(permitted_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(permitted_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to administrator_articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def permitted_params
    params.require(:article).
      permit(:title, :subtitle, :body, :published, :author_id, :hero_image_name, :featured)
  end
end

app/controllers/administrator/authors_controller.rb
# frozen_string_literal: true

class Administrator::AuthorsController < Administrator::BaseController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.active.paginate(page: params[:page])
  end

  def show; end

  def new
    @author = Author.new
  end

  def edit; end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to administrator_author_path(@author), notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to administrator_author_path(@author), notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to administrator_authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_author
    @author = Author.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def author_params
    params.require(:author).permit(:name, :email, :active, :twitter, :about)
  end
end

app/controllers/administrator/base_controller.rb
# frozen_string_literal: true

class Administrator::BaseController < ApplicationController
  before_action :authenticate, if: -> { Rails.env.production? }

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "dox_blog" && password == "hgf765"
    end
  end
end

app/controllers/administrator/pages_controller.rb
# frozen_string_literal: true

class Administrator::PagesController < Administrator::BaseController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.published.paginate(page: params[:page])
  end

  def new
    @page = Page.new
  end

  def edit; end

  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to administrator_pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :subtitle, :body, :published, :author_id, :hero_image_name, :featured)
  end
end

app/views/administrator/pages/_form.html.slim
.big
  = form_for @page, url: (@page.persisted?? administrator_page_path(@page) : administrator_pages_path) do |form|
    - if @page.errors.any?
      .error_explanation
        p = "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
        ul
          - @page.errors.full_messages.each do |message|
            li = message
    p
      = form.label :title do
      = form.text_field :title
    p
      = form.label :subtitle do
      = form.text_field :subtitle
    p
      = form.label :hero_image_name do
      = form.text_field :hero_image_name
    p
      = form.label :body do
      = form.text_area :body, rows: '20'
    p
      = form.label :published do
      = form.check_box :published
    p
      = form.label :featured do
      = form.check_box :featured
    p
      = form.label :author do
      = collection_select(:page, :author_id, Author.active, :id, :name, prompt: true)
    p
      = form.submit

app/views/administrator/pages/edit.html.slim
.row
  .section
    h1 Editing Page
    hr
    = render 'form'
    hr
    = link_to 'Preview Page', page_path(@page), class: 'btn'
    =< link_to 'Cancel', administrator_pages_path, class: 'btn gray no-outline'

app/views/administrator/pages/index.html.slim
- provide :body_class do
  | articles-list articles

= render "layouts/admin_menu"

.row
  .section

    = link_to 'New Page', new_administrator_page_path, class: 'btn'
    hr

    .col-3-4
      - @pages.each do |page|
        .article
          h1 = page.title
          p.meta
            > Author:
            = page.author.name
            span.stick<
              > |
            > Published:
            = page.published
          p
            => link_to 'Preview', page_path(page), class: 'btn small'
            => link_to 'Edit', edit_administrator_page_path(page), class: 'btn small'
            => link_to 'Destroy', administrator_page_path(page), data: { confirm: 'Are you sure?' }, method: :delete, class: 'btn small red'
        hr
    .col-1-4

.row
  .section
    = will_paginate

app/views/administrator/pages/new.html.slim
.row
  .section
    h1 New Page
    hr
    = render 'form'
    hr
    = link_to 'Cancel', administrator_pages_path, class: 'btn'