config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get '/search' => 'articles#search'

  resources :pages, only: [:index, :show]
  resources :articles do
    collection do
      get :search_suggestions
    end
  end

  resources :authors, only: [:index]

  get 'components' => 'components#components', as: :components
  get 'admin' => 'administrator/articles#index', as: :admin

  namespace :administrator do
    resources :authors
    resources :articles, except: :show
    resources :pages, except: :show
  end
end

app/views/layouts/_admin_menu.html.slim
.row
  .section
    .tabs
      ul
        li class="#{'here' if current_page?(administrator_articles_path)}"
          = link_to "Articles", administrator_articles_path
        li class="#{'here' if current_page?(administrator_pages_path)}"
          = link_to "Pages", administrator_pages_path
        li class="#{'here' if current_page?(administrator_authors_path)}"
          = link_to "Authors", administrator_authors_path

app/views/layouts/_contents.html.slim
.contents

  - if @hero_asset || content_for(:hero)
    = render 'layouts/hero'

  = yield

app/views/layouts/_footer.html.slim
.row.footer.center
  .section
    .logo
      = image_tag 'logo-inverted.png'
    hr.quarter

    ul
      li = link_to "Doximity API", "https://www.doximity.com/developers/home"
      li.line |
      li = link_to "Open Source", "https://github.com/doximity"
      li.lime |
      li = link_to "Follow Us", "https://twitter.com/dox_engineering"

    hr.quarter
    p
      ' &copy;
      = Time.now.strftime('%Y')

app/views/layouts/_google_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-68519809-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/_header.html.slim
.row.header data-sel-delta-scroll=""
  .section
    = link_to root_path, class: 'logo'  do
      = image_tag 'logo.png'
    - if page = Page.friendly.find_by_slug("about-doximity")
      = link_to page_path(page), class: here_class?("pages", "show", "about-doximity") do
        > About
        span.hide-on-mobile
          | Doximity
    = link_to authors_path, class: here_class?("authors", "index")  do
        > Authors
    = link_to "https://workat.doximity.com", target: "_blank" do
      > We're Hiring

app/views/layouts/_hero.html.slim
.row.hero

  - if @hero_link
    = link_to @hero_link do
      .section
        = yield :hero

  - else
    .section
      = yield :hero

app/views/layouts/_hero_asset.html.slim
- if @hero_asset
  - content_for :style do
    css:
      .hero {
        background-image: url("#{asset_path(@hero_asset)}");
        box-shadow: inset 0 -4em 10em rgba(0,0,0,0.5)
      }

app/views/layouts/_notice.html.slim
- @notice_class = "show"
- @notice_class = "hide" if (yield(:notice).blank? && flash.empty?)

- if (:notice)
  .row.notice#notice class="#{@notice_class}"
    .section.autogrid
      .autocol
        = notice
      .autocol
        i.ion-ios-close-outline.i2x.float-right onclick="document.getElementById('notice').className = 'hide'; return false;" title="Dismiss"

app/views/layouts/_social.html.slim
share-button

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name='og:title' content="#{content_for(:title)}"
    meta name='og:image' content="#{content_for(:hero_image)}"
    title Doximity Engineering Blog
    - if content_for?(:meta)
      = yield :meta
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Raleway:100,200,400', media: 'all'
    = stylesheet_link_tag 'https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css', media: 'all'
    = stylesheet_link_tag 'share-button.min', media: 'all'
    = stylesheet_link_tag 'application', media: 'all'
    - if content_for?(:style)
      = yield :style
    = javascript_include_tag 'application'
    = javascript_include_tag 'share-button.min'
    = javascript_include_tag :defaults
    = csrf_meta_tags
    = favicon_link_tag
    = favicon_link_tag "apple-touch-icon-60x60.png", rel: "apple-touch-icon", type: "image/png", sizes: "60x60"
    = favicon_link_tag "apple-touch-icon-76x76.png", rel: "apple-touch-icon", type: "image/png", sizes: "76x76"
    = favicon_link_tag "apple-touch-icon-120x120.png", rel: "apple-touch-icon", type: "image/png", sizes: "120x120"
    = favicon_link_tag "apple-touch-icon-152x152.png", rel: "apple-touch-icon", type: "image/png", sizes: "152x152"

    = yield :head
  body class="#{yield(:body_class)}" id="#{controller_name}_#{action_name}"
    .wrap
      = render 'layouts/notice'
      = render 'layouts/header'
      = render 'layouts/contents'
      = render 'layouts/footer'
    = render 'layouts/google_analytics'